[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["alembic upgrade head"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
